/**
 * Response shape from https://api.rss2json.com/v1/api.json
 * Used in RssService to strongly-type HttpClient responses.
 */

export interface Rss2JsonFeed {
  url: string;
  title: string;
  link: string;
  author: string;
  description: string;
  /** Feed-level image URL (often the blog logo) */
  image: string;
}

export interface Rss2JsonItem {
  title: string;
  pubDate: string;
  link: string;
  guid: string;
  author: string;
  /** Thumbnail image extracted by rss2json from the post content */
  thumbnail: string;
  /** Short HTML description / excerpt */
  description: string;
  /** Full HTML content (not used — summaries are generated by Claude) */
  content: string;
  enclosure: Rss2JsonEnclosure;
  categories: string[];
}

export interface Rss2JsonEnclosure {
  link?: string;
  type?: string;
  thumbnail?: string;
}

export interface Rss2JsonResponse {
  status: 'ok' | 'error';
  feed: Rss2JsonFeed;
  items: Rss2JsonItem[];
  /** Present when status === 'error' */
  message?: string;
}
